Add support for defining and playing songs
AutonomyLab/create_autonomy pull request #37
Opened 2017-03-27 00:29 UTC by clydemcqueen

Add support for defining and playing songs. Tested on a Create 2.

The Create 2 Open Interface Spec is somewhat confusing: it says that you can create "up to four songs," but then suggests that song numbers can be "0 - 4". In my tests the only valid song numbers are 0, 1, 2 and 3.

2017-03-27 02:40 UTC, jacobperron requested changes
Thanks for the PR!

2017-03-27 02:40 UTC, jacobperron commented on ca_driver/src/create_driver.cpp
> +  robot_->defineSong(msg->song, msg->length, &(msg->notes.front()), &(msg->durations.front()));
This function returns a bool. At the very least we can check the return type and output an error message on failure. Something like `ROS_ERROR_STREAM("[CREATE] Failed to define song " << msg->song << " of length " << msg->length);`

2017-03-27 02:40 UTC, jacobperron commented on ca_driver/src/create_driver.cpp
> +  robot_->playSong(msg->song);
Same here with the bool value returned.

2017-03-27 02:40 UTC, jacobperron commented on ca_msgs/CMakeLists.txt
> +  DefineSong.msg
Alphabetize this list.

2017-03-27 02:40 UTC, jacobperron commented on ca_msgs/msg/DefineSong.msg
> +Header header         # ignored
Remove the header field if it's not useful.

2017-03-27 02:40 UTC, jacobperron commented on ca_msgs/msg/PlaySong.msg
> +Header header   # ignored
Similarly, remove this header too.

2017-03-27 15:56 UTC, clydemcqueen commented on ca_driver/src/create_driver.cpp
> +  robot_->defineSong(msg->song, msg->length, &(msg->notes.front()), &(msg->durations.front()));
Done. It would be nice to add more error checking to libcreate create::Create::defineSong. Perhaps that is a 2nd PR.

2017-03-27 15:56 UTC, clydemcqueen commented on ca_driver/src/create_driver.cpp
> +  robot_->playSong(msg->song);
Done.

2017-03-27 15:56 UTC, clydemcqueen commented on ca_msgs/CMakeLists.txt
> +  DefineSong.msg
Done.

2017-03-27 15:56 UTC, clydemcqueen commented on ca_msgs/msg/DefineSong.msg
> +Header header         # ignored
Done.

2017-03-27 15:56 UTC, clydemcqueen commented on ca_msgs/msg/PlaySong.msg
> +Header header   # ignored
Done.

2017-03-27 16:38 UTC, jacobperron approved these changes

2017-03-27 16:43 UTC, jacobperron commented
Looks great :+1: 

Finally, could you squash the latest commits and update the README (adding the new topics to the subscribers section). Cheers!

2017-03-28 01:12 UTC, clydemcqueen commented
OK! README updated and commits squashed. Thanks.

2017-04-09 23:23 UTC, merged